"""add groq_api_key_enc to ai_global_settings

Revision ID: 2db05e05006e
Revises: e5f6a7b8c9d0
Create Date: 2026-08-03 14:16:24.650192

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '2db05e05006e'
down_revision: Union[str, Sequence[str], None] = 'e5f6a7b8c9d0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ai_global_settings', sa.Column('groq_api_key_enc', sqlmodel.sql.sqltypes.AutoString(length=1024), nullable=True))
    op.add_column('ai_global_settings', sa.Column('groq_model', sqlmodel.sql.sqltypes.AutoString(length=256), nullable=True))
    op.alter_column('chat_sessions', 'system_prompt',
               existing_type=sa.VARCHAR(length=65535),
               type_=sqlmodel.sql.sqltypes.AutoString(length=8000),
               existing_nullable=True)
    op.alter_column('chat_sessions', 'context_summary',
               existing_type=sa.VARCHAR(length=65535),
               type_=sqlmodel.sql.sqltypes.AutoString(length=16000),
               existing_nullable=True)
    op.add_column('company_llm_settings', sa.Column('groq_api_key_enc', sqlmodel.sql.sqltypes.AutoString(length=1024), nullable=True))
    op.add_column('company_llm_settings', sa.Column('groq_model', sqlmodel.sql.sqltypes.AutoString(length=256), nullable=True))
    op.drop_index(op.f('ix_users_password_reset_token_hash'), table_name='users')
    op.drop_constraint(op.f('users_email_key'), 'users', type_='unique')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=False)
    op.create_unique_constraint(op.f('users_email_key'), 'users', ['email'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('ix_users_password_reset_token_hash'), 'users', ['password_reset_token_hash'], unique=True)
    op.drop_column('company_llm_settings', 'groq_model')
    op.drop_column('company_llm_settings', 'groq_api_key_enc')
    op.alter_column('chat_sessions', 'context_summary',
               existing_type=sqlmodel.sql.sqltypes.AutoString(length=16000),
               type_=sa.VARCHAR(length=65535),
               existing_nullable=True)
    op.alter_column('chat_sessions', 'system_prompt',
               existing_type=sqlmodel.sql.sqltypes.AutoString(length=8000),
               type_=sa.VARCHAR(length=65535),
               existing_nullable=True)
    op.drop_column('ai_global_settings', 'groq_model')
    op.drop_column('ai_global_settings', 'groq_api_key_enc')
    # ### end Alembic commands ###
