"""descricao

Revision ID: 504f62376127
Revises: 4b9819ada206
Create Date: 2026-07-30 14:58:09.676633

"""
from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = '504f62376127'
down_revision: str | Sequence[str] | None = '4b9819ada206'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###
