"""add context_summary to chat_sessions

Revision ID: 9874bae75773
Revises: ed3c3a337768
Create Date: 2026-07-30 16:16:32.992892

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9874bae75773'
down_revision: Union[str, Sequence[str], None] = 'ed3c3a337768'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat_sessions', sa.Column('context_summary', sa.String(length=65535), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chat_sessions', 'context_summary')
    # ### end Alembic commands ###
