**
!apps/
apps/*
!apps/backend/
!apps/backend/**

apps/backend/.env
apps/backend/.git
apps/backend/.mypy_cache
apps/backend/.pytest_cache
apps/backend/.ruff_cache
apps/backend/.turbo
apps/backend/.venv
apps/backend/**/__pycache__
apps/backend/**/*.py[cod]
apps/backend/tests
